language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
services:
  - mysql
  - redis-server
before_script:
  - mysql -e "create database ratelimit;" -uroot
  - mysql -e "CREATE TABLE `ratelimit` (`id` int(10) unsigned NOT NULL AUTO_INCREMENT, `_key` varchar(256) NOT NULL, `data` varchar(32) NOT NULL, `deadline` int(10) unsigned NOT NULL, PRIMARY KEY (`id`), UNIQUE KEY `_key` (`_key`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;" -uroot
  - composer install
script: phpunit --coverage-text
